### ISSUE TITLE
Add support for `genre` field

### ISSUE THREAD

**Issue by Iorvethe** [typst/biblatex#66]
The [`genre`](https://github.com/typst/hayagriva/blob/main/docs/file-format.md#genre) field is supported in the Hayagriva format, but unfortunately it seems that it is not parsed when using a `bibtex` references file. For example, if I format the following file with Hayagriva 0.8.0:

```bib
@thesis{Shamos_1978,
  title={Computational Geometry},
  author={Shamos, Michael Ian},
  genre={PhD. Thesis},
  publisher={Yale University},
  year={1978},
}
```

the resulting `yml` file is:

```yml
Shamos_1978:
  type: thesis
  title: Computational Geometry
  author: Shamos, Michael Ian
  date: 1978
  publisher: Yale University
```

I assume that the issue is with the conversion from `bibtex`, which is why I report the bug in the present repo. Let me know if it’s not, so I can move it to the appropriate place.
